// constants/errorCodes.js

export const ERROR_CODES = {
  // 공통
  NETWORK_ERROR: 'NETWORK_ERROR',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',

  // 인증
  UNAUTHORIZED: 'UNAUTHORIZED',
  LOGIN_FAILED: 'LOGIN_FAILED',

  // 사용자
  EMAIL_DUPLICATED: 'EMAIL_DUPLICATED',

  // 거래
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
}